### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by lozn00** [ygavrishov/SA.CodeView#2]
![image](https://user-images.githubusercontent.com/14260426/46595514-4eaf7300-cb0b-11e8-9c8b-e40611cc3065.png)
canot edit. code

**Comment by ygavrishov** [comment]
To turn on editing feature on **SA.CodeView** just change its ReadOnly property. Default value is **true** because initially it was developed as viewer but now it can be used as editor too.

![enable-editing](https://user-images.githubusercontent.com/1516228/46905613-09ba8080-ceff-11e8-90de-35f9fc39d648.png)

**Comment by lozn00** [comment]
thank, 



After DLL is generated today, drag and drop CodeView into the window to prompt errors.

**Comment by ygavrishov** [comment]
Please try latest version from master, it should not generate errors.
